---
title: "Assignment 2"
---

```{r setup, include=FALSE}
#Installing and Loading the required packages
library(tidyverse)
library(RMySQL)

#Connecting to the database - MySQL, created a new connection with the Login Name: dbuser and Password: cunyspsdata607. This would be one way to share just this connection with relevant users

mydb = dbConnect(MySQL(),user='dbuser',password='cunyspsdata607',dbname='movies',host='localhost')
dbListTables(mydb)
```

## R Markdown
```{r avg_movie_review}
#There are three different tables movie, rating and reviewer. movie_id is the primary key in the movie table, reviewer_id is the primary key in the reviewer table and rating_id is the primary key in the rating table. The rating table references movie_id and reviewer_id as foreign keys. 

#Load the information from the three SQL tables into an R dataframe using the select statement.
getresults <- data.frame(dbGetQuery(mydb, "Select movie_name, reviewer_last_name, reviewer_first_name, rating 
        from movie, reviewer, rating
        where movie.movie_id = rating.movie_id and
        reviewer.reviewer_id = rating.reviewer_id
        order by movie_name, reviewer_last_name, reviewer_first_name, rating"))

#Display results of the resultant dataframe

getresults

#Group results by movie name, this is helpful at first glance to retrieve ratings by reviewer for each movie.

gb_movie_name <- group_by(getresults, movie_name)

#But what would be really useful is to see the average rating for each movie...

avg_movie_review <- summarize(gb_movie_name, count = n(), rating = mean(round(rating), na.rm=TRUE))
avg_movie_review

#There is one reviewer who hasn't reviewed any movies and we set that value to 0.

avg_movie_review$rating[is.nan(avg_movie_review$rating)] <- 0

#Finally, we plot and analyze the data. Among the survey responses, The King's Speech had the highest rating while Almost Famous came a close second.

ggplot(data = avg_movie_review) + geom_bar(mapping = aes(x = movie_name, y = rating), stat = "identity")

```